---
title: "NYPD"
author: "Anon"
date: "11/3/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r library, message=FALSE}
##install.packages(tidyverse,lubridate,ggplot2,caTools)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(caTools)
```

```{r NYPD Shooting Incident Data}
## Current data files
## The data is from the website https://catalog.data.gov/dataset/nypd-shooting-incident-data-historic. Each incident is a row. Columns provide information such as longitude and latitude, Borough, time and date, Precinct, Victim age, race and gender, perpetrator age, race and gender, etc.

url_in <- "https://data.cityofnewyork.us/api/views/833y-fsy8/rows.csv?accessType=DOWNLOAD"
```

```{r import data}
## Using the data provided, I want to find out if an incident case is dependent on the area, day and demographic of victims and perpetrators. 

incident_cases <- read.csv(url_in)
summary(incident_cases)
```

```{r tidy data}
## First eliminating columns I will not use for my analysis. There is missing data in few of the columns which has to be dealt with.

incident_cases_1 <- incident_cases %>%
  select(INCIDENT_KEY,
         OCCUR_DATE, 
         OCCUR_TIME, 
         BORO, PRECINCT, 
         STATISTICAL_MURDER_FLAG, 
         PERP_AGE_GROUP,
         PERP_SEX,
         PERP_RACE,
         VIC_AGE_GROUP,
         VIC_SEX,
         VIC_RACE)

glimpse(incident_cases_1)

## The blank cells in the columns PERP_AGE_GROUP, PERP_SEX, PERP_RACE of the data which  are replaced with NA

incident_cases_1[incident_cases_1 == ""] <- NA

table(is.na(incident_cases_1))
summary(sapply(incident_cases_1, is.na))
```

```{r transform_data}
## The columns of PERP_AGE_GROUP, PERP_SEX, PERP_RACE have NA which I then replace with the character "UNKNOWN". This is because I want to use the data without bias.

incident_cases_1 <- incident_cases_1 %>% replace_na(list(PERP_AGE_GROUP = "UNKNOWN", PERP_SEX = "U", PERP_RACE = "UNKNOWN"))

## Remove extreme values from PERP_AGE_GROUP
incident_cases_1 <- subset(incident_cases_1, PERP_AGE_GROUP!="1020" & PERP_AGE_GROUP!="224" & PERP_AGE_GROUP!="940")

## I parse the date and time values and then extract the day and hour so that it would be easier to use for my analysis
incident_cases_1$OCCUR_DAY = mdy(incident_cases_1$OCCUR_DATE)
incident_cases_1$OCCUR_DAY = wday(incident_cases_1$OCCUR_DAY, label = TRUE)
incident_cases_1$OCCUR_HOUR = hour(hms(as.character(incident_cases_1$OCCUR_TIME)))
```

```{r analysis 1}
## Two visuals for analysis

## Q1. What race of victims occurs the most and what boro are most victims found?
## For analysis, I wanted to know what race of victims are from each Borough. From the visual, a large number of victims are black and found in Brooklyn   

plot1 <- ggplot(incident_cases_1, aes(BORO)) +
  geom_bar(aes(fill = VIC_RACE), width = 0.5) + 
  theme_classic() +
  labs(title = "Histogram on Race of Victims per Area", x = "Boro", y = "Count")

plot1

```

```{r analysis 2}
## Q2. What day(s) do the most incidents occur?
## By plotting each incident based on the day it occured, I found that most incidents happened on the weekend. 

plot2 <- ggplot(incident_cases_1, aes(OCCUR_DAY)) + 
  geom_bar(width = 0.5) +
  theme_classic() + 
  labs( title="Chart of Incident Cases per Day")

plot2
  
```

```{r model, message = FALSE}
## I want to predict whether the incident case is a murder or not. For the model, I use Logistic Regression. I divide the data into two sets - the training set and the test set. Based on the prediction, I can find if my model is accurate or not from the matrix.

split <- sample.split(incident_cases_1, SplitRatio = 0.8)
split

train <- subset(incident_cases_1, split == "TRUE")
test <- subset(incident_cases_1, split == "FALSE")

logistic_model <- glm(STATISTICAL_MURDER_FLAG ~ OCCUR_DAY + OCCUR_HOUR + BORO + PERP_AGE_GROUP + PERP_SEX + PERP_RACE, data = train, family = "binomial")

summary(logistic_model)

pred <- predict(logistic_model, test, type = "response")

## Accuracy can be calculated using the formula [(True Positive + True Negative) / (True Positive + True Negative + False Positive + False Negative)]
## Accuracy of my model is 81.68%

table(test$STATISTICAL_MURDER_FLAG, pred > 0.5)
```  

```{r identify bias, message = FALSE}
## Conclusion
## Overall, incident cases seemed to depend on the area and the day. The race and age of victim and perpetrator also made a difference in the analysis. However, a lot of perpetrator data is unknown, since they may have not been caught.

## Looking at the visualisations and the data, the possible sources of bias might be on race, age and gender. Based on my personal judgement, I might conclude that most victims are female since there is always articles on violence against women. However, based on the data, there are many incidents that occur to men as well. Instead of assuming things, I should make informed decisions using data-driven methods.

```